### ISSUE TITLE
Oswan not working

### ISSUE THREAD

**Issue by XargonWan** [RafaVico/RG350_APPREPOSITORY#2]
The Oswan build that you're providing is not working tests:
- from SimpleMenu: rom not launching (app not opening?)
- from app (GMenu): app not opening
- tried .zip, .ws, .wsc roms

**Comment by RafaVico** [comment]
In gmenu2x works ok.
App don't open, when you start emulator the rom selector is launched. Tested with .ws roms: Armored Unit, Beat Mania and others.

**Comment by XargonWan** [comment]
Tried again: whenever I open a rom by opening the emulator first it goes back to the rom list.

**Comment by XargonWan** [comment]
Ok seems like that the .zip roms are not working, I tought I tested ws and wsc but I was wrong.
Working.
