### ISSUE TITLE
Race is not compatible with SimpleMenu

### ISSUE THREAD

**Issue by XargonWan** [RafaVico/RG350_APPREPOSITORY#3]
I suggest you a Race (Neo Geo Pocket) version that is compatible with SimpleMen as the rom can be called with param.
Can you add it?

https://github.com/retrogamehandheld/OpenDingux/raw/master/Emulators/Race(Explorer)_2019-12-11.opk

Source: https://github.com/retrogamehandheld/OpenDingux

**Comment by RafaVico** [comment]
Yes, this version works ok. I'll add it to repository.
Thanks.
