### ISSUE TITLE
Genesis Plus GX

### ISSUE THREAD

**Issue by XargonWan** [RafaVico/RG350_APPREPOSITORY#4]
The Sega CD roms are not loaded, tried:
- from SimpleMenu: rom not launching
- from app (GMenu): app is opening but rom is not launching (just goes back to the roms selection screen)
- tried .bin, .cue

**Comment by RafaVico** [comment]
Tested with gmenu2x and works ok, it opened all megadrive roms I launched. Only tested .bin roms.
How do you download the files and put into console?

**Comment by XargonWan** [comment]
My games are in sdcard/roms/Sega CD, the same folder that they were prior the ROGUE firmware installation.

Before I had OFW and those .bin files were running correctly, so that's why I was thinking that maybe that Genesis Plus GX version have some issues.

**Comment by XargonWan** [comment]
After ROGUE installation BIOS were missing, fixed by putting the BIOSes.
